//! GBA programmable timers (TM0..TM3).
//!
//! Timers advance from CPU cycles. Timer 0 is the source for the non-cascade
//! chain; later timers can count the overflow edge of their predecessor.

pub const TIMER_COUNT: usize = 4;
pub const TIMER0CNT_L: u32 = 0x0400_0100;
pub const TIMER0CNT_H: u32 = 0x0400_0102;
pub const TIMER1CNT_L: u32 = 0x0400_0104;
pub const TIMER1CNT_H: u32 = 0x0400_0106;
pub const TIMER2CNT_L: u32 = 0x0400_0108;
pub const TIMER2CNT_H: u32 = 0x0400_010a;
pub const TIMER3CNT_L: u32 = 0x0400_010c;
pub const TIMER3CNT_H: u32 = 0x0400_010e;

const PRESCALE: [u32; 4] = [1, 64, 256, 1024];
pub const CONTROL_PRESCALER_MASK: u16 = 0b11;
pub const CONTROL_CASCADE: u16 = 1 << 2;
pub const CONTROL_IRQ: u16 = 1 << 6;
pub const CONTROL_ENABLE: u16 = 1 << 7;

#[derive(Debug, Clone, Copy, PartialEq, Eq, Default)]
pub struct TimerControl {
    pub prescaler: u8,
    pub cascade: bool,
    pub irq: bool,
    pub enable: bool,
}

impl TimerControl {
    pub const fn from_raw(raw: u16) -> Self {
        Self {
            prescaler: (raw & CONTROL_PRESCALER_MASK) as u8,
            cascade: raw & CONTROL_CASCADE != 0,
            irq: raw & CONTROL_IRQ != 0,
            enable: raw & CONTROL_ENABLE != 0,
        }
    }

    pub const fn raw(self) -> u16 {
        (self.prescaler as u16 & CONTROL_PRESCALER_MASK)
            | if self.cascade { CONTROL_CASCADE } else { 0 }
            | if self.irq { CONTROL_IRQ } else { 0 }
            | if self.enable { CONTROL_ENABLE } else { 0 }
    }

    #[inline]
    pub const fn period(self) -> u32 {
        let index = if self.prescaler > 3 { 3 } else { self.prescaler };
        PRESCALE[index as usize]
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum TimerState {
    Stopped,
    Running,
}

#[derive(Debug, Clone, Copy, Default)]
pub struct Timer {
    reload: u16,
    counter: u16,
    control: TimerControl,
    cycle_accumulator: u32,
}

impl Timer {
    pub fn reload(&self) -> u16 {
        self.reload
    }

    pub fn counter(&self) -> u16 {
        self.counter
    }

    pub fn control(&self) -> TimerControl {
        self.control
    }

    pub fn state(&self) -> TimerState {
        if self.control.enable {
            TimerState::Running
        } else {
            TimerState::Stopped
        }
    }

    pub fn write_reload(&mut self, value: u16) {
        self.reload = value;
    }

    pub fn write_control(&mut self, raw: u16) {
        let next = TimerControl::from_raw(raw);
        if !self.control.enable && next.enable {
            self.counter = self.reload;
            self.cycle_accumulator = 0;
        } else if self.control.enable && !next.enable {
            self.cycle_accumulator = 0;
        }
        self.control = next;
    }

    pub fn read_control(&self) -> u16 {
        self.control.raw()
    }

    /// Advance an externally-clocked timer and return the number of overflow
    /// edges generated by this operation.
    pub fn tick_cycles(&mut self, cycles: u32) -> u32 {
        if !self.control.enable || self.control.cascade {
            return 0;
        }
        self.cycle_accumulator = self.cycle_accumulator.saturating_add(cycles);
        let period = self.control.period();
        let increments = self.cycle_accumulator / period;
        self.cycle_accumulator %= period;
        self.increment_ticks(increments)
    }

    /// Advance a timer from cascade edges generated by its predecessor.
    pub fn tick_cascade(&mut self, increments: u32) -> u32 {
        if !self.control.enable || !self.control.cascade || increments == 0 {
            return 0;
        }
        self.increment_ticks(increments)
    }

    fn increment_ticks(&mut self, increments: u32) -> u32 {
        if increments == 0 {
            return 0;
        }

        // The first overflow is measured from the current counter. Every
        // subsequent overflow starts from the reload value, so its distance is
        // 0x1_0000 - reload rather than a fixed 0x1_0000.
        let first_overflow_at = 0x1_0000u32 - self.counter as u32;
        if increments < first_overflow_at {
            self.counter = self.counter.wrapping_add(increments as u16);
            return 0;
        }

        let remaining = increments - first_overflow_at;
        let period_after_reload = 0x1_0000u32 - self.reload as u32;
        let extra_overflows = remaining / period_after_reload;
        let remainder = remaining % period_after_reload;
        self.counter = if remainder == 0 {
            self.reload
        } else {
            self.reload.wrapping_add(remainder as u16)
        };
        1 + extra_overflows
    }
}

pub const fn timer_index(address: u32) -> Option<usize> {
    match address & !1 {
        TIMER0CNT_L | TIMER0CNT_H => Some(0),
        TIMER1CNT_L | TIMER1CNT_H => Some(1),
        TIMER2CNT_L | TIMER2CNT_H => Some(2),
        TIMER3CNT_L | TIMER3CNT_H => Some(3),
        _ => None,
    }
}

pub const fn timer_register_is_control(address: u32) -> bool {
    matches!(
        address & !1,
        TIMER0CNT_H | TIMER1CNT_H | TIMER2CNT_H | TIMER3CNT_H
    )
}

pub const fn timer_base(index: usize) -> Option<u32> {
    match index {
        0 => Some(TIMER0CNT_L),
        1 => Some(TIMER1CNT_L),
        2 => Some(TIMER2CNT_L),
        3 => Some(TIMER3CNT_L),
        _ => None,
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn enabling_timer_loads_reload_value() {
        let mut timer = Timer::default();
        timer.write_reload(0xff00);
        timer.write_control(CONTROL_ENABLE);
        assert_eq!(timer.counter(), 0xff00);
    }

    #[test]
    fn prescaler_accumulator_preserves_partial_cycles() {
        let mut timer = Timer::default();
        timer.write_reload(0);
        timer.write_control(CONTROL_ENABLE | 1);
        assert_eq!(timer.tick_cycles(63), 0);
        assert_eq!(timer.counter(), 0);
        assert_eq!(timer.tick_cycles(1), 0);
        assert_eq!(timer.counter(), 1);
    }

    #[test]
    fn overflow_reloads_and_reports_one_edge() {
        let mut timer = Timer::default();
        timer.write_reload(0xfffe);
        timer.write_control(CONTROL_ENABLE);
        assert_eq!(timer.tick_cycles(1), 0);
        assert_eq!(timer.counter(), 0xffff);
        assert_eq!(timer.tick_cycles(1), 1);
        assert_eq!(timer.counter(), 0xfffe);
    }

    #[test]
    fn multiple_ticks_after_reload_use_reload_based_overflow_period() {
        let mut timer = Timer::default();
        timer.write_reload(0xfffe);
        timer.write_control(CONTROL_ENABLE);
        assert_eq!(timer.tick_cycles(4), 2);
        assert_eq!(timer.counter(), 0xfffe);
    }

    #[test]
    fn cascade_mode_counts_predecessor_overflows() {
        let mut timer = Timer::default();
        timer.write_reload(0xffff);
        timer.write_control(CONTROL_ENABLE | CONTROL_CASCADE);
        assert_eq!(timer.tick_cascade(1), 1);
        assert_eq!(timer.counter(), 0xffff);
        assert_eq!(timer.tick_cascade(1), 1);
        assert_eq!(timer.counter(), 0xffff);
    }

    #[test]
    fn control_write_does_not_expose_reserved_bits() {
        let mut timer = Timer::default();
        timer.write_control(0xffff);
        assert_eq!(timer.read_control(), 0x00c7);
    }

    #[test]
    fn timer_register_mapping_includes_high_byte_accesses() {
        assert_eq!(timer_index(TIMER0CNT_L), Some(0));
        assert_eq!(timer_index(TIMER0CNT_L + 1), Some(0));
        assert_eq!(timer_index(TIMER0CNT_H), Some(0));
        assert_eq!(timer_index(TIMER0CNT_H + 1), Some(0));
        assert!(timer_register_is_control(TIMER0CNT_H));
        assert!(timer_register_is_control(TIMER0CNT_H + 1));
        assert!(!timer_register_is_control(TIMER0CNT_L + 1));
    }
}
