use std::fmt::Write;

use crate::cfg::Program;
use crate::decoder::Mode;
use crate::ir::{IrOp, Value};

#[derive(Debug, Clone)]
pub struct RustModule {
    pub source: String,
}

fn value(v: &Value) -> String {
    match v { Value::Reg(r) => format!("rt.cpu.r[{r}]"), Value::Imm(v) => format!("{v:#x}") }
}

fn emit_op(out: &mut String, op: &IrOp) {
    match op {
        IrOp::Nop => { let _ = writeln!(out, "    rt.tick(1);"); }
        IrOp::Mov { dst, src } => { let _ = writeln!(out, "    rt.cpu.r[{dst}] = {};", value(src)); }
        IrOp::Add { dst, lhs, rhs } => { let _ = writeln!(out, "    rt.cpu.r[{dst}] = rt.cpu.r[{lhs}].wrapping_add({});", value(rhs)); }
        IrOp::Sub { dst, lhs, rhs } => { let _ = writeln!(out, "    rt.cpu.r[{dst}] = rt.cpu.r[{lhs}].wrapping_sub({});", value(rhs)); }
        IrOp::Cmp { lhs, rhs } => { let _ = writeln!(out, "    rt.compare(rt.cpu.r[{lhs}], {});", value(rhs)); }
        IrOp::Load { dst, base, offset, byte } => {
            if *byte { let _ = writeln!(out, "    rt.cpu.r[{dst}] = rt.read8(rt.cpu.r[{base}].wrapping_add({offset}i32 as u32)) as u32;"); }
            else { let _ = writeln!(out, "    rt.cpu.r[{dst}] = rt.read32(rt.cpu.r[{base}].wrapping_add({offset}i32 as u32));"); }
        }
        IrOp::Store { src, base, offset, byte } => {
            if *byte { let _ = writeln!(out, "    rt.write8(rt.cpu.r[{base}].wrapping_add({offset}i32 as u32), rt.cpu.r[{src}] as u8);"); }
            else { let _ = writeln!(out, "    rt.write32(rt.cpu.r[{base}].wrapping_add({offset}i32 as u32), rt.cpu.r[{src}]);"); }
        }
        IrOp::Branch { target, condition, link } => {
            if *link { let _ = writeln!(out, "    rt.cpu.r[14] = rt.cpu.r[15].wrapping_add(4);"); }
            if condition == &crate::decoder::Condition::Al { let _ = writeln!(out, "    return rt.dispatch({target:#010x});"); }
            else { let _ = writeln!(out, "    if rt.condition({:?}) {{ return rt.dispatch({target:#010x}); }}", condition); }
        }
        IrOp::BranchExchange { register, link } => {
            if *link { let _ = writeln!(out, "    rt.cpu.r[14] = rt.cpu.r[15].wrapping_add(4);"); }
            let _ = writeln!(out, "    return rt.dispatch(rt.cpu.r[{register}] & !1);");
        }
        IrOp::Unknown { address, raw, mode } => {
            let mode = match mode { Mode::Arm => "Arm", Mode::Thumb => "Thumb" };
            let _ = writeln!(out, "    rt.unimplemented({address:#010x}, {raw:#010x}, \"{mode}\");");
        }
    }
}

pub fn generate(program: &Program, module_name: &str) -> RustModule {
    let mut out = String::new();
    let _ = writeln!(out, "// @generated by gba-recompiler; do not edit.\n");
    let _ = writeln!(out, "use gba_runtime::Runtime;\n");
    let _ = writeln!(out, "pub fn {module_name}(rt: &mut Runtime) -> ! {{ rt.dispatch({:#010x}) }}\n", program.cfg.blocks[program.entry.0].key.address);
    for block in &program.cfg.blocks {
        if block.instructions.is_empty() { continue; }
        let _ = writeln!(out, "#[inline(always)]");
        let _ = writeln!(out, "pub fn block_{:08x}(rt: &mut Runtime) -> ! {{", block.key.address);
        for ins in &block.ir { for op in &ins.ops { emit_op(&mut out, op); } }
        let fallthrough = block.successors.first().copied();
        match fallthrough {
            Some(next) if block.ir.iter().flat_map(|i| i.ops.iter()).any(|o| matches!(o, IrOp::Branch { .. } | IrOp::BranchExchange { .. })) => {
                let _ = writeln!(out, "    unreachable!();");
                let _ = next;
            }
            Some(next) => {
                let target = program.cfg.blocks[next.0].key.address;
                let _ = writeln!(out, "    rt.dispatch({target:#010x})");
            }
            None => { let _ = writeln!(out, "    rt.halt()" ); }
        }
        let _ = writeln!(out, "}}\n");
    }
    RustModule { source: out }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::{analyze, decoder::{Mode, ROM_BASE}};

    #[test]
    fn emits_rust_for_cfg() {
        let rom = 0xE1A0_0000u32.to_le_bytes().to_vec();
        let program = analyze(&rom, ROM_BASE, Mode::Arm).unwrap();
        let generated = generate(&program, "entry");
        assert!(generated.source.contains("block_08000000"));
        assert!(generated.source.contains("gba_runtime::Runtime"));
    }
}
