use thiserror::Error;

pub const ROM_BASE: u32 = 0x0800_0000;
pub const ROM_END: u32 = 0x0E00_0000;

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Mode { Arm, Thumb }

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum OpcodeKind {
    Branch { target: u32, link: bool },
    BranchExchange { register: u8 },
    DataProcessing,
    LoadStore,
    Other,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct Instruction { pub address: u32, pub mode: Mode, pub raw: u32, pub kind: OpcodeKind, pub size: u8 }

#[derive(Debug, Error)]
pub enum DecodeError { #[error("truncated instruction at {0:#x}")] Truncated(u32) }

pub fn decode_arm(address: u32, raw: u32) -> Instruction {
    let link = (raw & (1 << 24)) != 0;
    let is_branch = (raw & 0x0e00_0000) == 0x0a00_0000;
    let kind = if is_branch {
        let imm = ((raw & 0x00ff_ffff) as i32) << 8 >> 6;
        OpcodeKind::Branch { target: address.wrapping_add(8).wrapping_add(imm as u32), link }
    } else if (raw & 0x0fff_fff0) == 0x012f_ff10 {
        OpcodeKind::BranchExchange { register: (raw & 0xf) as u8 }
    } else if (raw & 0x0c00_0000) == 0x0400_0000 { OpcodeKind::LoadStore }
    else if (raw & 0x0c00_0000) == 0x0000_0000 { OpcodeKind::DataProcessing }
    else { OpcodeKind::Other };
    Instruction { address, mode: Mode::Arm, raw, kind, size: 4 }
}

pub fn decode_thumb(address: u32, raw: u16) -> Instruction {
    let kind = if (raw & 0xf800) == 0xe000 {
        let imm = (((raw & 0x07ff) as i32) << 21 >> 20) as u32;
        OpcodeKind::Branch { target: address.wrapping_add(4).wrapping_add(imm), link: false }
    } else { OpcodeKind::Other };
    Instruction { address, mode: Mode::Thumb, raw: raw as u32, kind, size: 2 }
}

#[derive(Debug, Clone)]
pub struct BasicBlock { pub start: u32, pub instructions: Vec<Instruction> }

#[derive(Debug, Clone, Default)]
pub struct Program { pub entry: u32, pub blocks: Vec<BasicBlock> }

pub fn analyze(rom: &[u8], entry: u32) -> Result<Program, DecodeError> {
    let offset = entry.wrapping_sub(ROM_BASE) as usize;
    if offset + 4 > rom.len() { return Err(DecodeError::Truncated(entry)); }
    let raw = u32::from_le_bytes(rom[offset..offset + 4].try_into().unwrap());
    Ok(Program { entry, blocks: vec![BasicBlock { start: entry, instructions: vec![decode_arm(entry, raw)] }] })
}

pub fn generate_rust(program: &Program) -> String {
    let mut out = String::from("// Generated by gba-recompiler. Do not edit.\nuse gba_runtime::Runtime;\n\n");
    for block in &program.blocks {
        out.push_str(&format!("#[inline(always)]\npub fn block_{:08x}(rt: &mut Runtime) {{\n", block.start));
        for ins in &block.instructions { out.push_str(&format!("    rt.trace_recompiled({:#010x}, {:#010x});\n", ins.address, ins.raw)); }
        out.push_str("}\n\n");
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;
    #[test] fn decodes_arm_branch() { let i = decode_arm(ROM_BASE, 0xea00_0000); assert!(matches!(i.kind, OpcodeKind::Branch { .. })); }
    #[test] fn decodes_thumb_branch() { let i = decode_thumb(ROM_BASE, 0xe000); assert!(matches!(i.kind, OpcodeKind::Branch { .. })); }
}
