mod arm;
mod blocks;
mod common;
mod dispatcher;
mod linking;
mod operands;
mod ops;
mod terminators;
mod thumb;

pub use common::RustModule;

use crate::cfg::Program;
use crate::semantic_ir::SemanticProgram;

use blocks::emit_block;
use dispatcher::{emit_dispatcher, emit_linked_predicate};

pub fn generate_semantic(
    program: &Program,
    semantic: &SemanticProgram,
    module_name: &str,
) -> RustModule {
    assert!(
        !semantic.functions.is_empty(),
        "cannot generate an empty semantic program"
    );

    let mut out = String::new();
    use std::fmt::Write;

    let _ = writeln!(
        out,
        "// @generated by gba-recompiler; do not edit.\nuse gba_runtime::{{GeneratedBlockExit, Runtime}};\n"
    );

    let entry = &semantic.functions[semantic.entry.0];
    let entry_block = program
        .cfg
        .blocks
        .get(entry.entry.0)
        .expect("semantic entry block missing");
    let entry_address = entry_block.key.address;
    let entry_mode = matches!(entry_block.key.mode, crate::decoder::Mode::Thumb);

    let _ = writeln!(
        out,
        "#[allow(dead_code)]\npub fn {module_name}(rt: &mut Runtime) -> Result<gba_runtime::GeneratedExecutionResult, &'static str> {{\n    <Runtime as gba_runtime::RuntimeContract>::run_generated_contract(rt, {entry_address:#010x}, {entry_mode}, None, dispatch_block, is_linked_block)\n}}\n"
    );
    let _ = writeln!(
        out,
        "#[allow(dead_code)]\npub fn {module_name}_with_limit(rt: &mut Runtime, max_steps: u64) -> Result<gba_runtime::GeneratedExecutionResult, &'static str> {{\n    <Runtime as gba_runtime::RuntimeContract>::run_generated_contract(rt, {entry_address:#010x}, {entry_mode}, Some(max_steps), dispatch_block, is_linked_block)\n}}\n"
    );

    emit_dispatcher(&mut out, semantic);
    emit_linked_predicate(&mut out, semantic);
    for function in &semantic.functions {
        for block in &function.blocks {
            emit_block(&mut out, program, semantic, block.id);
        }
    }

    RustModule { source: out }
}

pub fn generate(program: &Program, module_name: &str) -> RustModule {
    let functions = crate::function::discover_functions(program);
    let semantic = crate::semantic_ir::build_semantic_program(program, &functions)
        .expect("program must satisfy the semantic execution contract before code generation");
    generate_semantic(program, &semantic, module_name)
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::{analyze, build_semantic_program, discover_functions, Mode, ROM_BASE};

    #[test]
    fn facade_preserves_generated_module_contract() {
        let mut rom = Vec::new();
        rom.extend_from_slice(&0xE3A0_0001u32.to_le_bytes());
        rom.extend_from_slice(&0xE280_0001u32.to_le_bytes());
        let program = analyze(&rom, ROM_BASE, Mode::Arm).unwrap();
        let functions = discover_functions(&program);
        let semantic = build_semantic_program(&program, &functions).unwrap();
        let module = generate_semantic(&program, &semantic, "entry");
        assert!(module.source.contains("fn dispatch_block"));
        assert!(module.source.contains("fn is_linked_block"));
        assert!(module.source.contains("rt.enter_instruction"));
        assert!(!module.source.contains("rt.execute_arm_instruction"));
        assert!(!module.source.contains("rt.execute_thumb_instruction"));
    }
}
